# Generated by Django 3.1 on 2020-10-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RideData',
            new_name='Ride',
        ),
    ]
