# Generated by Django 3.1 on 2020-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201007_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
