# Generated by Django 3.1 on 2020-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201007_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='duration',
        ),
    ]
