# Generated by Django 3.1 on 2020-10-09 17:04

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_ride_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.DurationField(default=timedelta()),
            preserve_default=False,
        ),
    ]
