# Generated by Django 3.1 on 2020-12-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(max_length=10)),
                ('ride_native_id', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elevation', models.IntegerField()),
                ('avg_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('avg_heart_rate', models.IntegerField(blank=True)),
                ('max_heart_rate', models.IntegerField(blank=True)),
                ('avg_watts', models.IntegerField(blank=True)),
                ('max_watts', models.IntegerField(blank=True)),
                ('avg_cadence', models.IntegerField(blank=True)),
                ('max_cadence', models.IntegerField(blank=True)),
                ('calories', models.PositiveSmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
