# Generated by Django 3.1 on 2021-06-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_auto_20201202_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_type', models.CharField(choices=[('weight', 'weight'), ('bp', 'bp')], max_length=25)),
                ('health_value1', models.IntegerField(blank=True)),
                ('health_value2', models.IntegerField(blank=True)),
                ('health_date', models.DateTimeField()),
                ('health_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
